@extends('student-portal.layout')
@section('heading', 'My registered courses')
@section('description', 'Review your current and previous semester courses, credit hours, and assigned teachers.')
@section('student-content')
    <form method="GET" class="portal-filter-bar">
        <div class="portal-filter-field"><label class="form-label" for="enrollment"><i class="bi bi-funnel me-1" aria-hidden="true"></i> Semester enrollment</label><select id="enrollment" name="enrollment" class="form-select"><option value="">All enrollments</option>@foreach($enrollments as $enrollment)<option value="{{ $enrollment->id }}" @selected(request('enrollment') == $enrollment->id)>{{ $enrollment->semester }} · {{ $enrollment->academic_year }} · {{ ucfirst($enrollment->status) }}</option>@endforeach</select></div>
        <button class="portal-btn" type="submit"><i class="bi bi-check2" aria-hidden="true"></i> Apply filter</button>
        @if(request()->filled('enrollment'))<a class="portal-btn is-outline" href="{{ route('student.courses') }}"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> Reset</a>@endif
    </form>
    <div class="table-responsive portal-table-card"><table class="table academic-table align-middle"><thead><tr><th>Course</th><th>Semester / term</th><th>Credits</th><th>Registration</th><th>Assigned teachers</th></tr></thead><tbody>@forelse($courses as $course)<tr><td class="portal-course-cell"><strong>{{ $course->course_name }}</strong><small>{{ $course->course_code }}</small></td><td><strong>{{ $course->enrollment->semester }}</strong><small>{{ $course->enrollment->academic_year }} · {{ $course->enrollment->term?->name ?? 'Historical enrollment' }}</small></td><td><span class="portal-badge is-info">{{ number_format((float) $course->credit_hours, 1) }} credits</span></td><td><span class="portal-badge">{{ ucfirst($course->registration_type ?? 'Registered') }}</span></td><td><i class="bi bi-person-video3 me-1 text-muted" aria-hidden="true"></i>{{ $course->offering?->teachers->pluck('name')->join(', ') ?: 'Not recorded' }}</td></tr>@empty<tr class="portal-empty-row"><td colspan="5"><div class="portal-empty-state"><i class="bi bi-journal-x" aria-hidden="true"></i><strong>No registered courses found</strong><span>Courses will appear after your semester registration is completed.</span></div></td></tr>@endforelse</tbody></table></div>
    <div class="portal-pagination">{{ $courses->links('pagination::bootstrap-5') }}</div>
@endsection
