@extends('academic.layout')
@section('workspace-eyebrow', 'ACADEMIC REPORTING')
@section('heading', 'Academic reports')
@section('description', 'Operational summaries based on saved enrollment, attendance, and published result records.')
@section('header-actions')<button class="btn academic-header-btn" onclick="window.print()"><i class="bi bi-printer"></i> Print report</button>@endsection
@section('workspace-navigation')<nav class="academic-tabs"><a class="active" href="{{ route('academic.reports.index') }}">Reports</a>@can('audit.view')<a href="{{ route('academic.audits.index') }}">Audit viewer</a>@endcan</nav>@endsection
@section('academic-content')
    <form method="GET" class="row g-3 mb-4 no-print"><div class="col-md-5"><label class="form-label" for="term">Academic term</label><select id="term" name="term" class="form-select"><option value="">All terms</option>@foreach($terms as $term)<option value="{{ $term->id }}" @selected(request('term') == $term->id)>{{ $term->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label" for="minimum_attendance">Attendance shortage threshold (%)</label><input id="minimum_attendance" name="minimum_attendance" class="form-control" type="number" min="0" max="100" step="0.01" value="{{ $threshold }}"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary">Refresh report</button></div></form>
    <div class="d-flex flex-wrap gap-4 border-top border-bottom py-3 mb-4"><span>Published results <strong>{{ $resultSummary['published'] }}</strong></span><span>Pass <strong>{{ $resultSummary['pass'] }}</strong></span><span>Fail <strong>{{ $resultSummary['fail'] }}</strong></span><span>Average SGPA <strong>{{ $resultSummary['average_sgpa'] ?? '—' }}</strong></span><span>Average percentage <strong>{{ $resultSummary['average_percentage'] ?? '—' }}{{ $resultSummary['average_percentage'] !== null ? '%' : '' }}</strong></span></div>
    <section class="academic-form-section"><h2>Teacher workload</h2><p class="text-muted">Each co-teacher assignment is shown; student counts are offering rosters, not duplicated course records.</p><div class="table-responsive"><table class="table academic-table"><thead><tr><th>Teacher(s)</th><th>Offering</th><th>Term / section</th><th>Enrolled students</th><th>Offering state</th></tr></thead><tbody>@forelse($workload as $row)<tr><td>{{ $row['teacher_names'] }}</td><td>{{ $row['course'] }}</td><td>{{ $row['term'] }} · {{ $row['section'] }}</td><td>{{ $row['students'] }}</td><td>{{ ucfirst($row['status']) }}</td></tr>@empty<tr><td colspan="5" class="academic-empty">No offerings match the selected term.</td></tr>@endforelse</tbody></table></div></section>
    <section class="academic-form-section"><h2>Attendance shortage</h2><p class="text-muted">Completed-session live attendance below {{ $threshold }}%. Excused sessions are excluded according to the stored attendance policy.</p><div class="table-responsive"><table class="table academic-table"><thead><tr><th>Student</th><th>Offering</th><th>Counted sessions</th><th>Attendance</th></tr></thead><tbody>@forelse($shortages as $row)<tr><td>{{ $row['student']->name }}<small>{{ $row['student']->registration_no }}</small></td><td>{{ $row['offering']->course_code }} · {{ $row['offering']->course_name }}</td><td>{{ $row['valid'] }}</td><td>{{ $row['percentage'] }}%</td></tr>@empty<tr><td colspan="4" class="academic-empty">No attendance shortages at this threshold.</td></tr>@endforelse</tbody></table></div></section>
    <section><h2>Promotion eligible students</h2><p class="text-muted">This report applies the current promotion policy. It does not promote students or select courses.</p><div class="table-responsive"><table class="table academic-table"><thead><tr><th>Student</th><th>Current semester</th><th>Published outcome</th><th>Next step</th></tr></thead><tbody>@forelse($promotion as $row)<tr><td>{{ $row['enrollment']->student->name }}<small>{{ $row['enrollment']->student->registration_no }}</small></td><td>{{ $row['enrollment']->semester }} · {{ $row['enrollment']->academic_year }}</td><td>{{ $row['enrollment']->semesterResult?->status }}</td><td><a href="{{ route('promoteEnrollmentForm', $row['enrollment']) }}">Open promotion</a></td></tr>@empty<tr><td colspan="4" class="academic-empty">No active enrollments currently meet promotion requirements.</td></tr>@endforelse</tbody></table></div></section>
@endsection
