@extends('academic.layout')
@section('workspace-eyebrow', 'ACADEMIC OVERSIGHT')
@section('heading', 'Academic audit viewer')
@section('description', 'Read-only evidence for attendance, assessment, and semester-result changes.')
@section('workspace-navigation')<nav class="academic-tabs">@can('reports.view')<a href="{{ route('academic.reports.index') }}">Reports</a>@endcan<a class="active" href="{{ route('academic.audits.index') }}">Audit viewer</a></nav>@endsection
@section('academic-content')
    <form method="GET" class="row g-3 mb-4"><div class="col-md-4"><label for="type" class="form-label">Record type</label><select id="type" class="form-select" name="type"><option value="">All audit records</option>@foreach(['result' => 'Result', 'assessment' => 'Assessment', 'attendance' => 'Attendance'] as $value => $label)<option value="{{ $value }}" @selected(request('type') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-5"><label for="search" class="form-label">Search action, actor, reason, or subject</label><input id="search" class="form-control" name="search" value="{{ request('search') }}" maxlength="100"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary">Filter</button></div></form>
    <div class="academic-note mb-3">Audit evidence is immutable operational history. It is not an editing screen and it deliberately does not expose student portals or teacher private views.</div>
    <div class="table-responsive"><table class="table academic-table align-middle"><thead><tr><th>When</th><th>Type / subject</th><th>Actor</th><th>Action</th><th>Reason</th><th>Saved evidence</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ $audit['at']?->format('d M Y H:i') ?? '—' }}</td><td>{{ $audit['type'] }}<small>{{ $audit['subject'] ?? 'Historical record' }}</small></td><td>{{ $audit['actor'] ?? 'Former account' }}</td><td>{{ str_replace('_', ' ', ucfirst($audit['action'])) }}</td><td>{{ $audit['reason'] ?? '—' }}</td><td><details><summary>Before / after</summary><pre class="text-wrap mt-2">{{ json_encode(['before' => $audit['before'], 'after' => $audit['after']], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></details></td></tr>@empty<tr><td colspan="6" class="academic-empty">No audit records match this filter.</td></tr>@endforelse</tbody></table></div>
@endsection
