<div class="row g-3">
    <div class="col-md-6"><label for="assessment-title" class="form-label">Assessment title</label><input id="assessment-title" class="form-control" name="title" maxlength="120" value="{{ old('title', $assessment->title ?? '') }}" placeholder="Assignment 1" required></div>
    <div class="col-md-6"><label for="assessment-date" class="form-label">Assessment date</label><input id="assessment-date" class="form-control" type="date" name="held_on" min="{{ $offering->term->starts_on->toDateString() }}" max="{{ $offering->term->ends_on->toDateString() }}" value="{{ old('held_on', isset($assessment) ? $assessment->held_on->toDateString() : today()->toDateString()) }}" required></div>
    <div class="col-md-6"><label for="assessment-maximum" class="form-label">Raw maximum (paper marks)</label><input id="assessment-maximum" class="form-control" type="number" name="maximum" min="0.01" max="10000" step="0.01" value="{{ old('maximum', $assessment->maximum ?? '') }}" required></div>
    <div class="col-md-6"><label for="assessment-weight" class="form-label">Weight (contribution to course marks)</label><input id="assessment-weight" class="form-control" type="number" name="weight" min="0.01" max="1000" step="0.01" value="{{ old('weight', $assessment->weight ?? '') }}" required></div>
    <div class="col-12"><label for="assessment-instructions" class="form-label">Instructions <span class="text-muted">(optional)</span></label><textarea id="assessment-instructions" class="form-control" name="instructions" maxlength="5000" rows="3">{{ old('instructions', $assessment->instructions ?? '') }}</textarea></div>
    <div class="col-md-6"><div class="form-check mt-4"><input type="hidden" name="submission_required" value="0"><input id="submission-required" class="form-check-input" type="checkbox" name="submission_required" value="1" @checked(old('submission_required', $assessment->submission_required ?? false))><label class="form-check-label" for="submission-required">Require student portal submission</label></div></div>
    <div class="col-md-6"><label for="submissions-due-at" class="form-label">Submission deadline</label><input id="submissions-due-at" class="form-control" type="datetime-local" name="submissions_due_at" min="{{ $offering->term->starts_on->format('Y-m-d') }}T00:00" max="{{ $offering->term->ends_on->format('Y-m-d') }}T23:59" value="{{ old('submissions_due_at', isset($assessment) && $assessment->submissions_due_at ? $assessment->submissions_due_at->format('Y-m-d\TH:i') : '') }}"></div>
</div>
